# Generated by Django 4.1.7 on 2023-03-30 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artikli", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stanje",
            name="datum",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
